apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromium-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/chromium-versions
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromium-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

